# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 斋
email: leenacl93@gmail.com
description: 不积跬步无以至千里
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://leenacl.github.io" # the base hostname & protocol for your site
twitter_username: leenacl93
github_username:  leenacl

# Build settings
markdown: kramdown
